'use client'

import {useEffect,useMemo,useRef,useState} from 'react'
import {CheckCircle2,FileImage,FileText,History,Plus,Printer,Save,Search,Trash2,Upload,X} from 'lucide-react'
import type {Classe,Devoir,Eleve,Note} from '@/lib/types'

type Criterion={id:string;name:string;score:number;max:number}
type Correction={id:string;createdAt:string;classeId:string;eleveId:string;devoirId:string;titre:string;type:string;text:string;appreciation:string;notes:string;criteria:Criterion[];fileName?:string}
type Props={classes:Classe[];eleves:Eleve[];devoirs:Devoir[];onAddNote:(note:Note)=>void}
const KEY='ep-corrections-v1'
const defaults=():Criterion[]=>[['Respect de la consigne',4],['Organisation et cohérence',4],['Richesse des idées',4],['Langue et vocabulaire',5],['Orthographe et présentation',3]].map(([name,max])=>({id:crypto.randomUUID(),name:String(name),score:0,max:Number(max)}))

export default function CorrectionCopies({classes,eleves,devoirs,onAddNote}:Props){
 const [items,setItems]=useState<Correction[]>([]),[view,setView]=useState<'edit'|'history'>('edit'),[currentId,setCurrentId]=useState<string|null>(null)
 const [classeId,setClasseId]=useState(classes[0]?.id??''),[eleveId,setEleveId]=useState(''),[devoirId,setDevoirId]=useState(''),[titre,setTitre]=useState(''),[type,setType]=useState('Production argumentative')
 const [text,setText]=useState(''),[appreciation,setAppreciation]=useState(''),[notes,setNotes]=useState(''),[criteria,setCriteria]=useState<Criterion[]>(defaults),[suggestions,setSuggestions]=useState<string[]>([]),[file,setFile]=useState<File|null>(null),[previewUrl,setPreviewUrl]=useState(''),[message,setMessage]=useState('')
 const inputRef=useRef<HTMLInputElement>(null)
 useEffect(()=>{try{setItems(JSON.parse(localStorage.getItem(KEY)||'[]'))}catch{}},[])
 useEffect(()=>()=>{if(previewUrl)URL.revokeObjectURL(previewUrl)},[previewUrl])
 const classStudents=useMemo(()=>eleves.filter(e=>e.classeId===classeId),[eleves,classeId]),classTasks=useMemo(()=>devoirs.filter(d=>d.classeId===classeId),[devoirs,classeId])
 const total=criteria.reduce((s,c)=>s+Math.min(c.score,c.max),0),max=criteria.reduce((s,c)=>s+c.max,0)
 const studentName=(id:string)=>{const e=eleves.find(x=>x.id===id);return e?`${e.prenom} ${e.nom}`:'Élève supprimé'}
 function notify(v:string){setMessage(v);window.setTimeout(()=>setMessage(''),2800)}
 function chooseFile(f?:File){if(!f)return;if(previewUrl)URL.revokeObjectURL(previewUrl);setFile(f);setPreviewUrl(URL.createObjectURL(f))}
 function analyze(){const value=text.trim();if(!value){notify('Saisissez d’abord le texte de la copie.');return}const words=value.split(/\s+/).filter(Boolean),sentences=value.split(/[.!?]+/).filter(s=>s.trim()),found:string[]=[]
  if(/\s{2,}/.test(value))found.push('Plusieurs espaces inutiles ont été repérés.')
  if(/[.!?][A-Za-zÀ-ÖØ-öø-ÿ]/.test(value))found.push('Il manque parfois une espace après un signe de ponctuation.')
  if(sentences.some(s=>s.trim().split(/\s+/).length>35))found.push('Une phrase est très longue : elle peut être divisée pour gagner en clarté.')
  const frequency:Record<string,number>={};words.map(w=>w.toLowerCase().replace(/[^a-zà-ÿ'-]/g,'')).filter(w=>w.length>4).forEach(w=>frequency[w]=(frequency[w]||0)+1)
  const repeated=Object.entries(frequency).filter(([,n])=>n>=4).sort((a,b)=>b[1]-a[1]).slice(0,3);if(repeated.length)found.push(`Mots souvent répétés : ${repeated.map(([w,n])=>`« ${w} » (${n} fois)`).join(', ')}.`)
  if(words.length>70&&!/\b(d'abord|ensuite|cependant|enfin|donc|ainsi|mais)\b/i.test(value))found.push('Le texte gagnerait en clarté avec davantage de connecteurs logiques.')
  if(!/[.!?]$/.test(value))found.push('Le passage ne se termine pas par un signe de ponctuation.')
  if(words.length<40)found.push(`Le texte est court (${words.length} mots) : vérifiez si les idées sont suffisamment développées.`)
  setSuggestions(found.length?found:['Aucune maladresse simple détectée. Une relecture grammaticale du professeur reste nécessaire.'])
 }
 function reset(){setCurrentId(null);setEleveId('');setDevoirId('');setTitre('');setType('Production argumentative');setText('');setAppreciation('');setNotes('');setCriteria(defaults());setSuggestions([]);setFile(null);if(previewUrl)URL.revokeObjectURL(previewUrl);setPreviewUrl('');setView('edit')}
 function save(){if(!eleveId){notify('Choisissez un élève.');return}if(!titre.trim()&&!devoirId){notify('Indiquez le devoir ou un titre.');return}const task=devoirs.find(d=>d.id===devoirId);const entry:Correction={id:currentId??crypto.randomUUID(),createdAt:new Date().toISOString(),classeId,eleveId,devoirId,titre:titre.trim()||task?.titre||'Correction',type,text,appreciation,notes,criteria,fileName:file?.name};const next=currentId?items.map(x=>x.id===currentId?entry:x):[entry,...items];setItems(next);localStorage.setItem(KEY,JSON.stringify(next));setCurrentId(entry.id);notify('Correction enregistrée sur cet appareil.')}
 function addToNotes(){if(!eleveId){notify('Choisissez un élève.');return}const label=titre.trim()||devoirs.find(d=>d.id===devoirId)?.titre||'Copie corrigée';onAddNote({id:crypto.randomUUID(),eleveId,libelle:label,valeur:Number(total.toFixed(2)),sur:Number(max.toFixed(2)),coefficient:1});notify('Note ajoutée dans la rubrique Notes.')}
 function open(item:Correction){setCurrentId(item.id);setClasseId(item.classeId);setEleveId(item.eleveId);setDevoirId(item.devoirId);setTitre(item.titre);setType(item.type);setText(item.text);setAppreciation(item.appreciation);setNotes(item.notes);setCriteria(item.criteria);setSuggestions([]);setFile(null);setPreviewUrl('');setView('edit')}
 function remove(id:string){if(!confirm('Supprimer cette correction ?'))return;const next=items.filter(x=>x.id!==id);setItems(next);localStorage.setItem(KEY,JSON.stringify(next));notify('Correction supprimée.')}
 function updateCriterion(id:string,field:keyof Criterion,value:string){setCriteria(criteria.map(c=>c.id===id?{...c,[field]:field==='name'?value:Math.max(0,Number(value)||0)}:c))}
 return <section className="cc-page">
  <div className="cc-actions"><button className="btn" onClick={reset}><Plus size={16}/> Nouvelle correction</button><button className="btn secondary" onClick={()=>setView('history')}><History size={16}/> Corrections enregistrées <span className="cc-count">{items.length}</span></button>{view==='edit'&&<><button className="btn secondary" onClick={save}><Save size={16}/> Enregistrer</button><button className="btn secondary" onClick={()=>window.print()}><Printer size={16}/> Imprimer / PDF</button></>}</div>
  {message&&<div className="cc-toast" role="status"><CheckCircle2 size={17}/>{message}</div>}
  {view==='history'?<section className="panel"><div className="panel-heading"><h2>Corrections enregistrées</h2></div>{items.length===0?<div className="empty">Aucune correction enregistrée.</div>:<div className="cc-history">{items.map(item=><article key={item.id} className="cc-history-card"><button onClick={()=>open(item)}><strong>{studentName(item.eleveId)}</strong><span>{item.titre} · {new Date(item.createdAt).toLocaleDateString('fr-FR')}</span></button><b>{sum(item.criteria)}/{sumMax(item.criteria)}</b><button className="action-btn delete" onClick={()=>remove(item.id)} aria-label={`Supprimer la correction de ${studentName(item.eleveId)}`}><Trash2 size={15}/></button></article>)}</div>}</section>:
  <><section className="panel cc-identity"><label>Classe<select className="input" value={classeId} onChange={e=>{setClasseId(e.target.value);setEleveId('');setDevoirId('')}}>{classes.map(c=><option key={c.id} value={c.id}>{c.nom} — {c.niveau}</option>)}</select></label><label>Élève<select className="input" value={eleveId} onChange={e=>setEleveId(e.target.value)}><option value="">Choisir un élève</option>{classStudents.map(e=><option key={e.id} value={e.id}>{e.prenom} {e.nom}</option>)}</select></label><label>Devoir<select className="input" value={devoirId} onChange={e=>setDevoirId(e.target.value)}><option value="">Autre devoir</option>{classTasks.map(d=><option key={d.id} value={d.id}>{d.titre}</option>)}</select></label><label>Titre<input className="input" value={titre} onChange={e=>setTitre(e.target.value)} placeholder="Ex. Production écrite 1"/></label><label>Type<select className="input" value={type} onChange={e=>setType(e.target.value)}><option>Production argumentative</option><option>Récit</option><option>Compréhension et langue</option><option>Correction libre</option></select></label></section>
  <div className="cc-grid"><section className="panel cc-copy"><div className="panel-heading"><h2>1. Copie de l’élève</h2><button className="btn secondary" onClick={()=>inputRef.current?.click()}><Upload size={16}/> Importer</button></div><input ref={inputRef} hidden type="file" accept="image/*,.pdf,application/pdf" onChange={e=>chooseFile(e.target.files?.[0])}/>{previewUrl?file?.type==='application/pdf'?<object className="cc-preview" data={previewUrl} type="application/pdf"><p>Utilisez votre lecteur PDF pour ouvrir la copie.</p></object>:<img className="cc-preview" src={previewUrl} alt="Copie importée"/>:<button className="cc-drop" onClick={()=>inputRef.current?.click()}><FileImage size={44}/><strong>Déposez ou importez la copie</strong><span>Photo JPG/PNG ou document PDF</span></button>}{file&&<div className="cc-file"><FileText size={15}/>{file.name}<button onClick={()=>{setFile(null);setPreviewUrl('')}} aria-label="Retirer le fichier"><X size={15}/></button></div>}</section>
  <section className="panel cc-correction"><h2>2. Correction et barème</h2><p className="helper">Pour une copie manuscrite, saisissez les passages à analyser. Vous validez toujours les remarques proposées.</p><label className="cc-label">Texte de l’élève<textarea className="input cc-text" value={text} onChange={e=>setText(e.target.value)} placeholder="Saisissez ou collez le texte…"/></label><button className="btn" onClick={analyze}><Search size={16}/> Analyser le texte</button>{suggestions.length>0&&<div className="cc-suggestions">{suggestions.map((s,i)=><div key={i}>{s}</div>)}</div>}<h3>Barème</h3><div className="cc-rubric">{criteria.map(c=><div key={c.id}><input aria-label="Critère" value={c.name} onChange={e=>updateCriterion(c.id,'name',e.target.value)}/><input aria-label={`Note pour ${c.name}`} type="number" min="0" max={c.max} step="0.25" value={c.score} onChange={e=>updateCriterion(c.id,'score',e.target.value)}/><span>/</span><input aria-label={`Maximum pour ${c.name}`} type="number" min="0.25" step="0.25" value={c.max} onChange={e=>updateCriterion(c.id,'max',e.target.value)}/></div>)}</div><button className="cc-add" onClick={()=>setCriteria([...criteria,{id:crypto.randomUUID(),name:'Nouveau critère',score:0,max:1}])}><Plus size={14}/> Ajouter un critère</button><div className="cc-total"><span>Note totale</span><strong>{trim(total)} / {trim(max)}</strong></div><button className="btn cc-note-btn" onClick={addToNotes}>Ajouter cette note dans « Notes »</button></section></div>
  <section className="panel cc-feedback"><label>Appréciation finale<textarea className="input" value={appreciation} onChange={e=>setAppreciation(e.target.value)} placeholder="Rédigez une appréciation personnalisée…"/></label><div className="cc-chips">{['Très bon travail.','Ensemble satisfaisant.','Des efforts à poursuivre.','Attention à l’orthographe.','Développez davantage vos idées.'].map(v=><button key={v} onClick={()=>setAppreciation(p=>(p?p+' ':'')+v)}>{v}</button>)}</div><label>Remarques détaillées<textarea className="input" value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Points réussis, erreurs récurrentes et conseils…"/></label></section></>}
 </section>
}
function sum(c:Criterion[]){return trim(c.reduce((s,x)=>s+Math.min(x.score,x.max),0))}function sumMax(c:Criterion[]){return trim(c.reduce((s,x)=>s+x.max,0))}function trim(n:number){return Number.isInteger(n)?String(n):n.toFixed(2).replace(/0$/,'')}
