'use client'

import {useEffect,useMemo,useRef,useState} from 'react'
import {CheckCircle2,FileImage,FileText,History,Plus,Printer,Save,Search,Trash2,Upload,X} from 'lucide-react'
import {supabase} from '@/lib/supabase/client'
import type {Classe,Devoir,Eleve,Note} from '@/lib/types'

type Criterion={id:string;name:string;score:number;max:number}
type Correction={id:string;createdAt:string;classeId:string;eleveId:string;devoirId:string;titre:string;type:string;text:string;appreciation:string;notes:string;criteria:Criterion[];fileName?:string;subject?:string;corrected?:string;report?:string}
type Props={classes:Classe[];eleves:Eleve[];devoirs:Devoir[];onAddNote:(note:Note)=>void}
const KEY='ep-corrections-v1'
const defaults=():Criterion[]=>[['Respect de la consigne',4],['Organisation et cohérence',4],['Richesse des idées',4],['Langue et vocabulaire',5],['Orthographe et présentation',3]].map(([name,max])=>({id:crypto.randomUUID(),name:String(name),score:0,max:Number(max)}))

export default function CorrectionCopies({classes,eleves,devoirs,onAddNote}:Props){
 const [items,setItems]=useState<Correction[]>([]),[view,setView]=useState<'edit'|'history'>('edit'),[currentId,setCurrentId]=useState<string|null>(null)
 const [classeId,setClasseId]=useState(classes[0]?.id??''),[eleveId,setEleveId]=useState(''),[devoirId,setDevoirId]=useState(''),[titre,setTitre]=useState(''),[type,setType]=useState('Production argumentative')
 const [text,setText]=useState(''),[appreciation,setAppreciation]=useState(''),[notes,setNotes]=useState(''),[criteria,setCriteria]=useState<Criterion[]>(defaults),[suggestions,setSuggestions]=useState<string[]>([]),[file,setFile]=useState<File|null>(null),[previewUrl,setPreviewUrl]=useState(''),[message,setMessage]=useState('')
 const [subject,setSubject]=useState(''),[corrected,setCorrected]=useState(''),[report,setReport]=useState(''),[busy,setBusy]=useState(''),[serviceReady,setServiceReady]=useState(false),[error,setError]=useState(''),[approved,setApproved]=useState(false)
 useEffect(()=>{fetch('/api/corrections').then(r=>r.json()).then(r=>setServiceReady(r.ready===true)).catch(()=>setError('Impossible de vérifier le service IA.'))},[])
 const inputRef=useRef<HTMLInputElement>(null)
 useEffect(()=>{try{setItems(JSON.parse(localStorage.getItem(KEY)||'[]'))}catch{}},[])
 useEffect(()=>()=>{if(previewUrl)URL.revokeObjectURL(previewUrl)},[previewUrl])
 const classStudents=useMemo(()=>eleves.filter(e=>e.classeId===classeId),[eleves,classeId]),classTasks=useMemo(()=>devoirs.filter(d=>d.classeId===classeId),[devoirs,classeId])
 const total=criteria.reduce((s,c)=>s+Math.min(c.score,c.max),0),max=criteria.reduce((s,c)=>s+c.max,0)
 const studentName=(id:string)=>{const e=eleves.find(x=>x.id===id);return e?`${e.prenom} ${e.nom}`:'Élève supprimé'}
 function notify(v:string){setMessage(v);window.setTimeout(()=>setMessage(''),2800)}
 function chooseFile(f?:File){if(!f)return;if(!['application/pdf','image/jpeg','image/png','image/webp'].includes(f.type)||f.size>2900000){setError('Choisissez un PDF, JPG, PNG ou WebP de moins de 3 Mo.');return;}setError('');if(previewUrl)URL.revokeObjectURL(previewUrl);setFile(f);setPreviewUrl(URL.createObjectURL(f))}
 async function analyze(action:'read'|'correct'){
  if(busy)return
  setError('')
  if(!serviceReady){setError('La correction IA attend son activation. Aucun document n’a été envoyé.');return}
  if(action==='read'&&!file){setError('Importez la copie avant de lancer la lecture.');return}
  if(action==='correct'&&(!text.trim()||!subject.trim())){setError('Renseignez la consigne et vérifiez le texte avant de corriger.');return}
  setBusy(action==='read'?'Lecture de la copie…':'Correction en cours…')
  try{
   const {data}=await supabase.auth.getSession()
   if(!data.session)throw new Error('Connectez-vous dans « Mes documents », puis revenez ici. Votre brouillon reste dans cet écran tant que vous ne changez pas de rubrique.')
   let encoded:string|undefined
   if(action==='read'&&file)encoded=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(new Error('Impossible de lire ce fichier.'));reader.readAsDataURL(file)})
   const response=await fetch('/api/corrections',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${data.session.access_token}`},body:JSON.stringify({action,file:encoded,text,subject,level:classes.find(c=>c.id===classeId)?.niveau||'Tronc commun',criteria:criteria.map(({id,name,max})=>({id,name,max}))})})
   const result=await response.json().catch(()=>({error:'Réponse interrompue ou fichier trop volumineux. Réessayez avec moins de 3 Mo.'}))
   if(!response.ok)throw new Error(result.error||'Échec de la correction.')
   setSuggestions(result.warnings||[]);setApproved(false)
   if(action==='read'){setText(result.transcription);setCorrected('');setReport('');notify('Texte extrait. Relisez les passages incertains, puis lancez la correction.')}
   else {setCorrected(result.corrected);setAppreciation(result.appreciation);setReport(result.errors.map((e:{original:string;correction:string;explanation:string})=>`« ${e.original} » → « ${e.correction} »
${e.explanation}`).join('\n\n'));if(result.scores.length){setCriteria(criteria.map(c=>({...c,score:result.scores.find((v:{id:string})=>v.id===c.id).score})));setNotes(result.scores.map((v:{id:string;reason:string})=>`${criteria.find(c=>c.id===v.id)?.name} : ${v.reason}`).join('\n'))}else setError('La copie ne permet pas de proposer une note fiable. Les notes déjà saisies restent inchangées.');notify('Proposition reçue : vérifiez-la avant de valider la note.')}
  }catch(e){setError(e instanceof Error?e.message:'La correction a échoué.')}
  finally{setBusy('')}
 }
 function reset(){if((text||file||subject)&&!confirm("Commencer une nouvelle correction ? Enregistrez d’abord votre travail si nécessaire."))return;setSubject('');setCorrected('');setReport('');setError('');setApproved(false);setCurrentId(null);setEleveId('');setDevoirId('');setTitre('');setType('Production argumentative');setText('');setAppreciation('');setNotes('');setCriteria(defaults());setSuggestions([]);setFile(null);if(previewUrl)URL.revokeObjectURL(previewUrl);setPreviewUrl('');setView('edit')}
 function save(){if(!eleveId){notify('Choisissez un élève.');return}if(!titre.trim()&&!devoirId){notify('Indiquez le devoir ou un titre.');return}const task=devoirs.find(d=>d.id===devoirId);const entry:Correction={id:currentId??crypto.randomUUID(),createdAt:new Date().toISOString(),classeId,eleveId,devoirId,titre:titre.trim()||task?.titre||'Correction',type,text,appreciation,notes,criteria,fileName:file?.name,subject,corrected,report};const next=currentId?items.map(x=>x.id===currentId?entry:x):[entry,...items];try{localStorage.setItem(KEY,JSON.stringify(next));setItems(next);setCurrentId(entry.id);notify('Correction enregistrée sur cet appareil.')}catch{setError('Stockage du navigateur plein ou inaccessible. Imprimez votre correction pour la conserver.')}}
 function addToNotes(){if(!currentId){notify('Enregistrez la correction avant de transférer sa note.');return;}if(!approved||max<=0){notify("Vérifiez la correction et cochez la validation du professeur.");return;}if(!eleveId){notify('Choisissez un élève.');return}const label=titre.trim()||devoirs.find(d=>d.id===devoirId)?.titre||'Copie corrigée';onAddNote({id:'correction-'+(currentId||crypto.randomUUID()),eleveId,libelle:label,valeur:Number(total.toFixed(2)),sur:Number(max.toFixed(2)),coefficient:1});notify('Note ajoutée dans la rubrique Notes.')}
 function open(item:Correction){setSubject(item.subject||'');setCorrected(item.corrected||'');setReport(item.report||'');setError('');setApproved(false);setCurrentId(item.id);setClasseId(item.classeId);setEleveId(item.eleveId);setDevoirId(item.devoirId);setTitre(item.titre);setType(item.type);setText(item.text);setAppreciation(item.appreciation);setNotes(item.notes);setCriteria(item.criteria);setSuggestions([]);setFile(null);setPreviewUrl('');setView('edit')}
 function remove(id:string){if(!confirm('Supprimer cette correction ?'))return;const next=items.filter(x=>x.id!==id);setItems(next);localStorage.setItem(KEY,JSON.stringify(next));notify('Correction supprimée.')}
 function updateCriterion(id:string,field:keyof Criterion,value:string){setApproved(false);setCriteria(criteria.map(c=>c.id===id?{...c,[field]:field==='name'?value:field==='max'?Math.max(0.25,Number(value)||0.25):Math.min(c.max,Math.max(0,Number(value)||0))}:c))}
 return <section className="cc-page">
  <div className="panel cc-no-print"><strong>{serviceReady?'Correction IA configurée':'Correction IA : activation nécessaire'}</strong><p>1. Importez la copie et lancez la lecture. 2. Vérifiez le texte et la consigne. 3. Corrigez, puis validez la note.</p><p>Le texte ou la copie sera transmis à OpenAI lorsque vous cliquerez sur un bouton IA. Masquez le nom sur la copie si possible. Les corrections enregistrées restent dans ce navigateur ; le fichier importé n’est pas conservé.</p></div>
  {error&&<div className="panel" role="alert">{error}</div>}
  {busy&&<p role="status">{busy} Veuillez patienter sans quitter la rubrique.</p>}
  <fieldset disabled={!!busy} style={{border:0,padding:0,margin:0,minWidth:0,display:'grid',gap:18}}>

  <div className="cc-actions"><button className="btn" onClick={reset}><Plus size={16}/> Nouvelle correction</button><button className="btn secondary" onClick={()=>setView('history')}><History size={16}/> Corrections enregistrées <span className="cc-count">{items.length}</span></button>{view==='edit'&&<><button className="btn secondary" onClick={save}><Save size={16}/> Enregistrer</button><button className="btn secondary" onClick={()=>window.print()}><Printer size={16}/> Imprimer / PDF</button></>}</div>
  {message&&<div className="cc-toast" role="status"><CheckCircle2 size={17}/>{message}</div>}
  {view==='history'?<section className="panel"><div className="panel-heading"><h2>Corrections enregistrées</h2></div>{items.length===0?<div className="empty">Aucune correction enregistrée.</div>:<div className="cc-history">{items.map(item=><article key={item.id} className="cc-history-card"><button onClick={()=>open(item)}><strong>{studentName(item.eleveId)}</strong><span>{item.titre} · {new Date(item.createdAt).toLocaleDateString('fr-FR')}</span></button><b>{sum(item.criteria)}/{sumMax(item.criteria)}</b><button className="action-btn delete" onClick={()=>remove(item.id)} aria-label={`Supprimer la correction de ${studentName(item.eleveId)}`}><Trash2 size={15}/></button></article>)}</div>}</section>:
  <><section className="panel cc-identity"><label>Classe<select className="input" value={classeId} onChange={e=>{setClasseId(e.target.value);setEleveId('');setDevoirId('')}}>{classes.map(c=><option key={c.id} value={c.id}>{c.nom} — {c.niveau}</option>)}</select></label><label>Élève<select className="input" value={eleveId} onChange={e=>setEleveId(e.target.value)}><option value="">Choisir un élève</option>{classStudents.map(e=><option key={e.id} value={e.id}>{e.prenom} {e.nom}</option>)}</select></label><label>Devoir<select className="input" value={devoirId} onChange={e=>setDevoirId(e.target.value)}><option value="">Autre devoir</option>{classTasks.map(d=><option key={d.id} value={d.id}>{d.titre}</option>)}</select></label><label>Titre<input className="input" value={titre} onChange={e=>setTitre(e.target.value)} placeholder="Ex. Production écrite 1"/></label><label>Type<select className="input" value={type} onChange={e=>setType(e.target.value)}><option>Production argumentative</option><option>Récit</option><option>Compréhension et langue</option><option>Correction libre</option></select></label></section>
  <div className="cc-grid"><section className="panel cc-copy"><div className="panel-heading"><h2>1. Copie de l’élève</h2><button className="btn secondary" onClick={()=>inputRef.current?.click()}><Upload size={16}/> Importer</button></div><input ref={inputRef} hidden type="file" accept="image/*,.pdf,application/pdf" onChange={e=>chooseFile(e.target.files?.[0])}/>{previewUrl?file?.type==='application/pdf'?<object className="cc-preview" data={previewUrl} type="application/pdf"><p>Utilisez votre lecteur PDF pour ouvrir la copie.</p></object>:<img className="cc-preview" src={previewUrl} alt="Copie importée"/>:<button className="cc-drop" onClick={()=>inputRef.current?.click()}><FileImage size={44}/><strong>Importer une copie</strong><span>Photo JPG/PNG ou document PDF</span></button>}{file&&<div className="cc-file"><FileText size={15}/>{file.name}<button onClick={()=>{setFile(null);setPreviewUrl('')}} aria-label="Retirer le fichier"><X size={15}/></button></div>}<button className="btn cc-no-print" disabled={!file||!serviceReady||!!busy} onClick={()=>void analyze('read')}>Lire automatiquement la copie</button></section>
  <section className="panel cc-correction"><h2>2. Correction et barème</h2><p className="helper">Après la lecture automatique, vérifiez la transcription ci-dessous. Les passages illisibles doivent être précisés avant la notation.</p><label className="cc-label">Consigne complète et attentes<textarea className="input" value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Collez le sujet, la longueur attendue et vos exigences…"/></label><label className="cc-label">Texte de l’élève<textarea className="input cc-text" value={text} onChange={e=>setText(e.target.value)} placeholder="Saisissez ou collez le texte…"/></label><button className="btn" onClick={()=>void analyze('correct')} disabled={!serviceReady||!!busy}><Search size={16}/> Corriger le texte avec l’IA</button>{suggestions.length>0&&<div className="cc-suggestions">{suggestions.map((s,i)=><div key={i}>{s}</div>)}</div>}<h3>Barème</h3><div className="cc-rubric">{criteria.map(c=><div key={c.id}><input aria-label="Critère" value={c.name} onChange={e=>updateCriterion(c.id,'name',e.target.value)}/><input aria-label={`Note pour ${c.name}`} type="number" min="0" max={c.max} step="0.25" value={c.score} onChange={e=>updateCriterion(c.id,'score',e.target.value)}/><span>/</span><input aria-label={`Maximum pour ${c.name}`} type="number" min="0.25" step="0.25" value={c.max} onChange={e=>updateCriterion(c.id,'max',e.target.value)}/></div>)}</div><button className="cc-add" onClick={()=>setCriteria([...criteria,{id:crypto.randomUUID(),name:'Nouveau critère',score:0,max:1}])}><Plus size={14}/> Ajouter un critère</button><div className="cc-total"><span>Note totale</span><strong>{trim(total)} / {trim(max)}</strong></div><label className="cc-no-print"><input type="checkbox" checked={approved} onChange={e=>setApproved(e.target.checked)}/> J’ai vérifié et validé la note.</label><button disabled={!approved} className="btn cc-note-btn" onClick={addToNotes}>Ajouter cette note dans « Notes »</button></section></div>
  <section className="panel"><h2>Texte corrigé proposé</h2><textarea className="input cc-text" value={corrected} onChange={e=>{setCorrected(e.target.value);setApproved(false)}} placeholder="La proposition apparaîtra après la correction IA."/><h3>Erreurs et explications</h3><textarea className="input cc-text" value={report} onChange={e=>{setReport(e.target.value);setApproved(false)}} placeholder="Les erreurs repérées et leurs explications apparaîtront ici."/></section><section className="panel cc-feedback"><label>Appréciation finale<textarea className="input" value={appreciation} onChange={e=>{setAppreciation(e.target.value);setApproved(false)}} placeholder="Rédigez une appréciation personnalisée…"/></label><div className="cc-chips">{['Très bon travail.','Ensemble satisfaisant.','Des efforts à poursuivre.','Attention à l’orthographe.','Développez davantage vos idées.'].map(v=><button key={v} onClick={()=>{setAppreciation(p=>(p?p+' ':'')+v);setApproved(false)}}>{v}</button>)}</div><label>Remarques détaillées<textarea className="input" value={notes} onChange={e=>{setNotes(e.target.value);setApproved(false)}} placeholder="Points réussis, erreurs récurrentes et conseils…"/></label></section></>}
 </fieldset></section>
}
function sum(c:Criterion[]){return trim(c.reduce((s,x)=>s+Math.min(x.score,x.max),0))}function sumMax(c:Criterion[]){return trim(c.reduce((s,x)=>s+x.max,0))}function trim(n:number){return Number.isInteger(n)?String(n):n.toFixed(2).replace(/0$/,'')}
